name = "agri-sync-worker"
main = "worker/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "agri-field-db"
database_id = "9c3735b3-e40b-4ebf-81a0-5ff6ca3d6843"

[[r2_buckets]]
binding = "MODELS"
bucket_name = "agri-models"